[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"

[colors.primary]
background = "#1a1b26"
foreground = "#a9b1d6"

[font]
size = 7.0

[font.bold]
family = "CaskaydiaCove Nerd Font Mono"
style = "Semibold"

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
style = "Semilight"

[font.offset]
x = 1
y = 1

[scrolling]
history = 5000

[window]
decorations = "full"
dynamic_title = false
opacity = 1
title = "îž• Alacritty"

[window.dimensions]
columns = 130
lines = 45

[window.padding]
x = 10
y = 10
